services:
  db:
    image: postgres:15-alpine
    container_name: olist_db
    restart: always
    shm_size: 1gb  # PostgreSQL shared memory için - büyük sorgular için gerekli
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - olist_network

  mlflow:
    build: .
    container_name: olist_mlflow
    restart: always
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      MLFLOW_DEFAULT_ARTIFACT_ROOT: ./mlruns
    command: mlflow server --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} --default-artifact-root ./mlruns --host 0.0.0.0 --serve-artifacts
    volumes:
      - ./mlruns:/mlruns
    depends_on:
      - db
    networks:
      - olist_network

  api:
    build: .
    container_name: olist_api
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - olist_network

  dashboard:
    build: .
    container_name: olist_dashboard
    command: streamlit run src/dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - db
      - api
    volumes:
      - .:/app
    networks:
      - olist_network

volumes:
  postgres_data:


networks:
  olist_network:
    driver: bridge
